language: rust
rust:
  - stable
  - beta
  - 1.30.0  # The minimal Rust version we claim we need.
before_script:
  # Get clippy-preview if clippy is not available for 1.30.0 not to break
  - rustup component add clippy || rustup component add clippy-preview
script:
  - cargo clippy -- -D warnings
  - cargo test --verbose
