[package]
name = "routinator"
version = "0.7.0-rc1-bis"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "An RPKI relying party software."
repository = "https://github.com/NLnetLabs/routinator"
keywords = ["rpki", "routing-security", "bgp"]
categories = ["command-line-utilities"]
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

[dependencies]
bytes           = "0.5.4"
chrono          = "0.4.11"
clap            = "2.33.0"
crossbeam-queue = "0.2.1"
crossbeam-utils = "0.7.2"
dirs            = "2.0.2"
fern		= "0.6.0"
futures         = "0.3.4"
hyper		= "0.13.4"
json		= "0.12.4"
listenfd	= "0.3.3"
log             = "0.4.8"
log-reroute	= "0.1.5"
num_cpus        = "1.12.0"
rand            = "0.7.3"
reqwest		= { version = "0.10.4", default-features = false, features = ["blocking"] }
ring		= "0.16.12"
rpki    	= "0.9.1"
rpki-rtr	= "0.1.0"
slab            = "0.4.2"
tempfile        = "3.1.0"
tokio           = { version = "0.2.16", features = [ "io-util", "macros", "signal", "sync" ] }
toml            = "0.5.6"
uuid            = "0.8.1"


[target.'cfg(unix)'.dependencies]
daemonize	= "0.4.1"
libc		= "0.2.68"
syslog		= "5.0.0"

[build-dependencies]
rustc_version   = "0.2.3"

[features]
default = ["rustls-tls", "socks"]
extra-debug = [ "rpki/extra-debug" ]
socks = [ "reqwest/socks" ]
native-tls = [ "reqwest/default-tls", "tls" ]
rustls-tls = [ "reqwest/rustls-tls", "tls" ]
tls = []

[package.metadata.deb]
maintainer = "The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
extended-description = """\
The Resource Public Key Infrastructure provides cryptographically signed \
statements about the association of Internet routing resources. \
In particular, it allows the holder of an IP address prefix to publish which \
AS number will be the origin of BGP route announcements for it. \
Routinator is a RPKI relying party software written in Rust. """
depends = "$auto, rsync"
section = "rust"
priority = "optional"
assets = [
    ["target/release/routinator", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/routinator/", "644"],
    ["doc/misc.md", "usr/share/doc/routinator/misc.md", "644"],
    ["doc/routinator.1", "usr/share/man/man1/routinator.1", "644"],
    ["etc/routinator.service", "lib/systemd/system/routinator.service", "644"],
    ["etc/routinator.conf.system-service", "etc/routinator/routinator.conf", "644"]
]
maintainer-scripts = "debian"

[package.metadata.deb.variants.minimal]
assets = [
    ["target/release/routinator", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/routinator/", "644"],
    ["doc/misc.md", "usr/share/doc/routinator/misc.md", "644"],
    ["doc/routinator.1", "usr/share/man/man1/routinator.1", "644"],
    ["etc/routinator.service.minimal", "lib/systemd/system/routinator.service", "644"],
    ["etc/routinator.conf.system-service", "etc/routinator/routinator.conf", "644"]
]

