[package]
# Note: some of these values are also used when building Debian packages below.
name = "routinator"
version = "0.9.0-dev"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "An RPKI relying party software."
repository = "https://github.com/NLnetLabs/routinator"
keywords = ["rpki", "routing-security", "bgp"]
categories = ["command-line-utilities"]
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

[dependencies]
bytes           = "1.0.0"
chrono          = "0.4.11"
clap            = "2.33.0"
crossbeam-queue = "0.3.1"
crossbeam-utils = "0.8.1"
dirs            = "3.0.1"
fern            = "0.6.0"
futures         = "0.3.4"
hyper           = { version = "0.14.2", features = [ "server", "stream" ] }
listenfd        = "0.3.3"
log             = "0.4.8"
log-reroute     = "0.1.5"
num_cpus        = "1.12.0"
rand            = "0.8.1"
reqwest         = { version = "0.11.0", default-features = false, features = ["blocking", "gzip"] }
ring            = "0.16.12"
rpki            = { git = "https://github.com/NLnetLabs/rpki-rs.git", features = [ "repository", "rrdp", "rtr" ] }
serde           = { version = "1.0.95", features = [ "derive" ] }
serde_json      = "1.0.57"
slab            = "0.4.2"
tempfile        = "3.1.0"
tokio           = { version = "1.0", features = [ "io-util", "macros", "rt-multi-thread", "signal", "sync" ] }
tokio-stream    = "0.1"
toml            = "0.5.6"
uuid            = "0.8.1"


[target.'cfg(unix)'.dependencies]
nix		= "0.19.1"
syslog          = "5.0.0"

[build-dependencies]
rustc_version   = "0.2.3"

[features]
default = ["rustls-tls", "socks"]
extra-debug = ["rpki/extra-debug"]
socks = [ "reqwest/socks" ]
rta = []
native-tls = [ "reqwest/native-tls", "tls" ]
rustls-tls = [ "reqwest/rustls-tls", "tls" ]
tls = []

[profile.release]
panic = "abort"

[package.metadata.deb]
name = "routinator"
maintainer = "The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
extended-description = """\
The Resource Public Key Infrastructure provides cryptographically signed \
statements about the association of Internet routing resources. \
In particular, it allows the holder of an IP address prefix to publish which \
AS number will be the origin of BGP route announcements for it. \
Routinator is a RPKI relying party software written in Rust. """
depends = "$auto, rsync, adduser"
section = "net"
priority = "optional"
assets = [
    ["target/release/routinator", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/routinator/", "644"],
    ["doc/misc.md", "usr/share/doc/routinator/misc.md", "644"],
    ["doc/routinator.1", "usr/share/man/man1/routinator.1", "644"],
    ["etc/routinator.conf.system-service", "etc/routinator/routinator.conf", "644"],
    ["debian/service.preset", "/lib/systemd/system-preset/50-routinator.preset", "644"],
    ["debian/routinator-init", "usr/bin/", "755"]
]
maintainer-scripts = "debian"
changelog = "debian/changelog" # this will be generated by the pkg workflow
copyright = "Copyright (c) 2020, NLnet Labs. All rights reserved."
conf-files = ["/etc/routinator/routinator.conf"]
systemd-units = { unit-name = "routinator", enable = false }

[package.metadata.deb.variants.minimal]
