[package]
name = "routinator"
version = "0.1.1"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "An RPKI relying party software."
repository = "https://github.com/NLnetLabs/routinator"
keywords = ["rpki", "routing-security", "bgp"]
categories = ["command-line-utilities"]
license = "BSD-3-Clause"

[dependencies]
bytes           = "^0.4"
chrono          = "^0.4"
clap            = "2.0"
daemonize	= "^0.3"
dirs            = "1.0"
env_logger      = "^0.5"
failure         = "^0.1"
futures         = "^0.1"
futures-cpupool = "^0.1"
json		= "^0.11"
lazy_static     = "1.1"
log             = "^0.4"
num_cpus        = "1.0"
rpki            = "^0.2.0"
slab            = "^0.4"
syslog		= "4.0"
tokio           = "^0.1"
tokio-process   = "^0.2"

[patch.crates-io]
rpki = { git = "https://github.com/NLnetLabs/rpki-rs.git" }
