[package]
name = "routinator"
version = "0.6.3"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "An RPKI relying party software."
repository = "https://github.com/NLnetLabs/routinator"
keywords = ["rpki", "routing-security", "bgp"]
categories = ["command-line-utilities"]
license = "BSD-3-Clause"
readme = "README.md"
build = "build.rs"

[dependencies]
bytes           = "^0.4"
chrono          = "^0.4"
clap            = "^2.0"
crossbeam-channel = "^0.4"
crossbeam-queue = "^0.1"
crossbeam-utils = "^0.6"
derive_more     = "^0.15"
dirs            = "^2.0"
fern		= "^0.5"
futures         = "^0.1"
hyper		= "^0.12.32"
json		= "^0.11"
listenfd	= "^0.3.3"
log             = "^0.4"
log-reroute	= "^0.1.2"
num_cpus        = "^1.0"
rand            = "^0.7"
reqwest		= { version = "^0.9.19", default-features = false, features = [ "rustls-tls", "socks" ]}
ring		= "^0.14"
rpki            = "^0.8.0"
serde		= "^1.0"
signal-hook     = "^0.1.11"
slab            = "^0.4"
tempfile        = "^3.1"
tokio           = "^0.1"
toml            = "^0.5"
unwrap          = "^1.2.1"
uuid            = "^0.7.4"

[target.'cfg(unix)'.dependencies]
daemonize	= "^0.4"
libc		= "^0.2"
syslog		= "^4.0"

[build-dependencies]
rustc_version   = "^0.2.3"

[features]
default = []
extra-debug = [ "rpki/extra-debug" ]

[package.metadata.deb]
maintainer = "The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
extended-description = """\
The Resource Public Key Infrastructure provides cryptographically signed \
statements about the association of Internet routing resources. \
In particular, it allows the holder of an IP address prefix to publish which \
AS number will be the origin of BGP route announcements for it. \
Routinator is a RPKI relying party software written in Rust. """
depends = "$auto, rsync"
section = "rust"
priority = "optional"
assets = [
    ["target/release/routinator", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/routinator/", "644"],
    ["doc/misc.md", "usr/share/doc/routinator/misc.md", "644"],
    ["doc/routinator.1", "usr/share/man/man1/routinator.1", "644"],
    ["etc/routinator.service", "lib/systemd/system/routinator.service", "644"],
    ["etc/routinator.conf.system-service", "etc/routinator/routinator.conf", "644"]
]
maintainer-scripts = "debian"

[package.metadata.deb.variants.minimal]
assets = [
    ["target/release/routinator", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/routinator/", "644"],
    ["doc/misc.md", "usr/share/doc/routinator/misc.md", "644"],
    ["doc/routinator.1", "usr/share/man/man1/routinator.1", "644"],
    ["etc/routinator.service.minimal", "lib/systemd/system/routinator.service", "644"],
    ["etc/routinator.conf.system-service", "etc/routinator/routinator.conf", "644"]
]

